default:
  image: jd91mzm2/nix-flakes
  before_script:
    # GitLab can't cache /nix directly
    - mkdir -p .nix
    - mount --bind /nix .nix
  cache:
    paths:
      - .nix

Build ISO:
  stage: build
  script:
    - nix flake check
    - nix build .#iso
    - cp result/iso/nixos.iso nixos.iso
  artifacts:
    expire_in: never
    paths:
      - nixos.iso
