default:
  image: jd91mzm2/nix-flakes
  before_script:
    # GitLab can't cache /nix directly
    - mkdir -p .nix
    - mount --bind /nix .nix
  cache:
    paths:
      - .nix

Build NeoVim:
  stage: build
  script:
    - nix build .#neovim -L

Build Simple Terminal:
  stage: build
  script:
    - nix build .#st -L
