default:
  image: jd91mzm2/nix-flakes
  before_script:
    # GitLab can't cache /nix directly
    - mkdir -p .nix
    - mount --bind /nix .nix
  cache:
    paths:
      - .nix

Build ISO:
  stage: build
  timeout: 2h
  script:
    - nix build .#iso -L

Publish ISO:
  stage: deploy
  timeout: 2h
  only:
    - master
    - ci
  script:
    - rclone config create BackBlaze b2 account "$B2_ID" key "$B2_KEY" hard_delete true
    - nix build .#iso -L
    - rclone sync result/iso/nixos.iso BackBlaze:jD91mZM2-public/nixos.iso
